version: "3.2"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./client:/usr/share/nginx/html

  flask:
    build: ./flask
    container_name: flask
    command: python server.py
    volumes:
      - ./flask:/usr/src/flask

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - ./dump:/dump
    restart: always


volumes:
  mongodata:
  nginx-log: